name: macos_ui
description: Flutter widgets and themes implementing the current macOS design language.
version: 0.9.3
homepage: "https://github.com/GroovinChip/macos_ui"

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  native_context_menu: ^0.1.2+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  dart_code_metrics: ^4.4.0
  mocktail: ^0.2.0

flutter:
  fonts:
    - family: SanFranciscoPro
      fonts:
        - asset: fonts/SFProTTF/SFProText-Regular.ttf
