name: macos_ui
description: Implements Apple's macOS Design System in Flutter. Based on the official documentation.
version: 0.0.4
homepage: 'https://github.com/GroovinChip/macos_ui'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  #split_view: ^1.0.4
  split_view:
    git:
      url: https://github.com/GroovinChip/split_view.git
      ref: null_safety

dev_dependencies:
  flutter_test:
    sdk: flutter
  dart_code_metrics: ^3.0.0

flutter:
  fonts:
    - family: SanFranciscoPro
      fonts:
        - asset: fonts/SFProTTF/SFProText-Regular.ttf