name: macos_ui
description: Flutter widgets and themes implementing the current macOS design language.
version: 0.1.3
homepage: 'https://github.com/GroovinChip/macos_ui'

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
dev_dependencies:
  flutter_test:
    sdk: flutter
  dart_code_metrics: ^3.2.3

flutter:
  fonts:
    - family: SanFranciscoPro
      fonts:
        - asset: fonts/SFProTTF/SFProText-Regular.ttf