name: Pana Analysis
on: [pull_request, workflow_dispatch]

jobs:
  package-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Install Flutter
        uses: subosito/flutter-action@master
        with:
          channel: stable

      #- name: Install dependencies
      #  run: flutter pub get

      - name: Run Code Metrics
        run: flutter pub global activate dart_code_metrics && flutter pub global run dart_code_metrics:metrics --reporter=github lib
      - uses: actions/checkout@v2

      - uses: axel-op/dart-package-analyzer@v3
        # set an id for the current step
        id: analysis
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}

      # You can then use this id to retrieve the outputs in the next steps.
      # The following step shows how to exit the workflow with an error if the total score in percentage is below 50:
      - name: Check scores
        env:
          # NB: "analysis" is the id set above. Replace it with the one you used if different.
          TOTAL: ${{ steps.analysis.outputs.total }}
          TOTAL_MAX: ${{ steps.analysis.outputs.total_max }}
        run: |
          PERCENTAGE=$(( $TOTAL * 100 / $TOTAL_MAX ))
          if (( $PERCENTAGE < 100 ))
          then
            echo Score too low!
            exit 1
          fi

      # This step is useful for PR's coming from forks. It takes the raw JSON and formats a report from it.
      - name: Format scores json
        env:
          JSON_OUTPUT: ${{ steps.analysis.outputs.json_output }}
        run: |
          TOTAL_SCORE=$(jq -r '.scores.grantedPoints' <<< "$JSON_OUTPUT")
